# -*- coding: utf-8 -*-
"""UnionDatosFinales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1FVfZNLh-YGYhXkvt8RFhK81HMOi3n96n
"""

from google.colab import drive
drive.mount('/content/drive')

# ═══════════════════════════════════════════════════════════════════════════════════
# SISTEMA DE CONSOLIDACIÓN V21.3 - FUSIÓN HISTÓRICA DE INACTIVOS + OPTIMIZADO + ORDEN
# ═══════════════════════════════════════════════════════════════════════════════════

print("📦 Instalando dependencias...")
import subprocess, sys
subprocess.check_call([sys.executable, "-m", "pip", "install", "-q",
                       "thefuzz", "python-Levenshtein",
                       "sentence-transformers", "scikit-learn",
                       "openpyxl", "pandas", "google-api-python-client",
                       "google-auth-httplib2", "google-auth-oauthlib"])
print("✅ Dependencias instaladas")

# ═══════════════════════════════════════════════════════════════════════════════════
# IMPORTACIONES
# ═══════════════════════════════════════════════════════════════════════════════════
import os, pandas as pd, numpy as np, json, re, unicodedata, shutil
from datetime import datetime
from collections import Counter, defaultdict
from thefuzz import fuzz
import warnings, gc, glob, hashlib
from google.colab import auth
from googleapiclient.discovery import build
from googleapiclient.http import MediaIoBaseDownload, MediaFileUpload
import io
warnings.filterwarnings('ignore')

USAR_IA_SEMANTICA = True
try:
    from sentence_transformers import SentenceTransformer
    from sklearn.metrics.pairwise import cosine_similarity
    print("✅ IA semántica disponible")
except Exception as e:
    USAR_IA_SEMANTICA = False
    print(f"⚠️ IA semántica no disponible: {e}")

# ═══════════════════════════════════════════════════════════════════════════════════
# DRIVE REMOTO Y CONFIGURACIÓN DE RUTAS
DRIVE_FOLDER_ID = os.getenv('COLAB_DRIVE_FOLDER_ID', 'SET_ME_IN_ENV')
DRIVE_MEMORIA_FILENAME = 'diccionario_columnas_v21.json'
DRIVE_CONFIG_MAPEO_FILENAME = 'config_mapeo_columnas_v21.json'
DRIVE_OUTPUT_FILENAME = 'CONSOLIDADO_SNAPSHOT_V21.csv'

REMOTE_DRIVE_TEMP = '/content/drive_remote'


def init_drive_service():
    try:
        auth.authenticate_user()
        return build('drive', 'v3')
    except Exception as e:
        print(f"⚠️ No se pudo inicializar el servicio de Drive: {e}")
        return None


def find_drive_file_id_by_name(name, parent_id):
    service = init_drive_service()
    if not service:
        return None
    try:
        query = f"name = '{name.replace("'", "\\'")}' and '{parent_id}' in parents and trashed = false"
        results = service.files().list(q=query, fields='files(id,name)').execute()
        files = results.get('files', [])
        return files[0]['id'] if files else None
    except Exception as e:
        print(f"⚠️ Error buscando archivo en Drive: {e}")
        return None


def download_drive_file_to_local(file_id, destination_path):
    service = init_drive_service()
    if not service:
        return False
    try:
        request = service.files().get_media(fileId=file_id)
        fh = io.FileIO(destination_path, mode='wb')
        downloader = MediaIoBaseDownload(fh, request)
        done = False
        while not done:
            status, done = downloader.next_chunk()
        return True
    except Exception as e:
        print(f"⚠️ Error descargando archivo Drive {file_id}: {e}")
        return False


def upload_local_file_to_drive(local_path, parent_folder_id, existing_file_id=None):
    service = init_drive_service()
    if not service:
        return False
    try:
        media = MediaFileUpload(local_path, resumable=True)
        file_metadata = {'name': os.path.basename(local_path), 'parents': [parent_folder_id]}
        if existing_file_id:
            updated = service.files().update(fileId=existing_file_id, media_body=media).execute()
            return updated.get('id')
        else:
            created = service.files().create(body=file_metadata, media_body=media, fields='id').execute()
            return created.get('id')
    except Exception as e:
        print(f"⚠️ Error subiendo archivo a Drive: {e}")
        return None


def download_drive_json(filename, destination_path):
    file_id = find_drive_file_id_by_name(filename, DRIVE_FOLDER_ID)
    if not file_id:
        print(f"ℹ️ Archivo no encontrado en Drive: {filename}")
        return False
    return download_drive_file_to_local(file_id, destination_path)


def upload_drive_json(filename, local_path):
    file_id = find_drive_file_id_by_name(filename, DRIVE_FOLDER_ID)
    return upload_local_file_to_drive(local_path, DRIVE_FOLDER_ID, existing_file_id=file_id)


def download_remote_memory_files():
    os.makedirs(os.path.dirname(RUTA_MEMORIA_JSON), exist_ok=True)
    if download_drive_json(DRIVE_MEMORIA_FILENAME, RUTA_MEMORIA_JSON):
        print(f"✅ Memoria columnas descargada desde Drive: {DRIVE_MEMORIA_FILENAME}")
    else:
        print(f"ℹ️ No se descargó memoria columnas remota; se usará local si existe.")
    if download_drive_json(DRIVE_CONFIG_MAPEO_FILENAME, RUTA_CONFIG_MAPEO):
        print(f"✅ Config de mapeo descargada desde Drive: {DRIVE_CONFIG_MAPEO_FILENAME}")
    else:
        print(f"ℹ️ No se descargó config de mapeo remota; se usará local si existe.")


def upload_remote_outputs():
    print(f"📤 Subiendo memoria y salida final a Drive ({DRIVE_FOLDER_ID})...")
    mem_id = upload_drive_json(DRIVE_MEMORIA_FILENAME, RUTA_MEMORIA_JSON)
    config_id = upload_drive_json(DRIVE_CONFIG_MAPEO_FILENAME, RUTA_CONFIG_MAPEO)
    output_id = upload_local_file_to_drive(RUTA_SALIDA, DRIVE_FOLDER_ID, existing_file_id=find_drive_file_id_by_name(DRIVE_OUTPUT_FILENAME, DRIVE_FOLDER_ID))
    if output_id:
        print(f"✅ Archivo de salida subido: {DRIVE_OUTPUT_FILENAME}")
    else:
        print(f"⚠️ No se pudo subir el archivo de salida a Drive")
    return {'memoria_id': mem_id, 'config_id': config_id, 'output_id': output_id}


def get_remote_source_file_list():
    service = init_drive_service()
    if not service:
        return []
    try:
        query = f"'{DRIVE_FOLDER_ID}' in parents and trashed = false and (mimeType = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet' or mimeType = 'application/vnd.ms-excel')"
        results = service.files().list(q=query, fields='files(id,name)').execute()
        return results.get('files', [])
    except Exception as e:
        print(f"⚠️ Error listando archivos remotos: {e}")
        return []


def sync_remote_source_files():
    os.makedirs(REMOTE_DRIVE_TEMP, exist_ok=True)
    files = get_remote_source_file_list()
    if not files:
        print(f"ℹ️ No se encontraron archivos Excel en la carpeta remota {DRIVE_FOLDER_ID}")
        return []
    paths = []
    for f in files:
        local_path = os.path.join(REMOTE_DRIVE_TEMP, f['name'])
        if os.path.exists(local_path):
            existing_hash = calcular_hash_archivo(local_path)
            if existing_hash and existing_hash == None:
                pass
        if download_drive_file_to_local(f['id'], local_path):
            paths.append(local_path)
    return paths

# ═══════════════════════════════════════════════════════════════════════════
# CONFIGURACIÓN DE RUTAS
# ═══════════════════════════════════════════════════════════════════════════════════
try:
    from google.colab import drive
    EN_COLAB = True
    BASE_DIR = '/content/drive/MyDrive'
    if not os.path.exists('/content/drive'):
        print("📌 Montando Google Drive...")
        drive.mount('/content/drive')
        print("✅ Google Drive montado")
    else:
        print("✅ Google Drive ya estaba montado")
except ImportError:
    EN_COLAB = False
    BASE_DIR = '.'
except Exception as e:
    print(f"⚠️ Error montando Drive: {e}")
    EN_COLAB = False
    BASE_DIR = '.'

if EN_COLAB:
    CARPETA_PROYECTO = f'{BASE_DIR}/SISTEMA_CONSOLIDACION_V21'
    os.makedirs(CARPETA_PROYECTO, exist_ok=True)

    RUTAS_ORIGEN      = [
        f'{BASE_DIR}/BASE DE DATOS/11. BASE SEGUIMIENTO PREDIAL 2025',
        f'{BASE_DIR}/BASE DE DATOS/12. BASE SEGUIMIENTO PREDIAL 2026'
    ]
    RUTA_SALIDA       = f'{CARPETA_PROYECTO}/CONSOLIDADO_SNAPSHOT_V21.csv'
    RUTA_MEMORIA_JSON = f'{CARPETA_PROYECTO}/diccionario_columnas_v21.json'
    RUTA_CONFIG_MAPEO = f'{CARPETA_PROYECTO}/config_mapeo_columnas_v21.json'
    RUTA_REPORT_TXT   = f'{CARPETA_PROYECTO}/REPORTE_PROCESO_V21.txt'
    RUTA_LOG          = f'{CARPETA_PROYECTO}/LOG_DETALLADO_V21.txt'
    RUTA_VALIDACIONES = f'{CARPETA_PROYECTO}/VALIDACIONES_PENDIENTES_V21.json'
    RUTA_TEMP         = f'{CARPETA_PROYECTO}/TEMP_CONSOLIDADO_V21'
    RUTA_MEMORIA_HOJAS= f'{CARPETA_PROYECTO}/memoria_hojas_v21.json'
    RUTA_MEMORIA_GEO  = f'{CARPETA_PROYECTO}/memoria_hojas_geo_v21.json'
    RUTA_PROGRESO     = f'{CARPETA_PROYECTO}/progreso_v21.json'
    RUTA_AUDITORIA_GEO= f'{CARPETA_PROYECTO}/auditoria_geo_v21.json'
else:
    RUTAS_ORIGEN      = ["./datos_entrada", "./datos_2025", "./datos_2026"]
    RUTA_SALIDA       = "./CONSOLIDADO_SNAPSHOT_V21.csv"
    RUTA_MEMORIA_JSON = "./diccionario_columnas_v21.json"
    RUTA_CONFIG_MAPEO = "./config_mapeo_columnas_v21.json"
    RUTA_REPORT_TXT   = "./REPORTE_PROCESO_V21.txt"
    RUTA_LOG          = "./LOG_DETALLADO_V21.txt"
    RUTA_VALIDACIONES = "./VALIDACIONES_PENDIENTES_V21.json"
    RUTA_TEMP         = "./TEMP_CONSOLIDADO_V21"
    RUTA_MEMORIA_HOJAS= "./memoria_hojas_v21.json"
    RUTA_MEMORIA_GEO  = "./memoria_hojas_geo_v21.json"
    RUTA_PROGRESO     = "./progreso_v21.json"
    RUTA_AUDITORIA_GEO= "./auditoria_geo_v21.json"

# ═══════════════════════════════════════════════════════════════════════════════════
# CONSTANTES
# ═══════════════════════════════════════════════════════════════════════════════════
UMBRAL_AUTO         = 95
UMBRAL_PREGUNTA_MIN = 85
PESO_NOMBRE         = 0.7
PESO_TIPO           = 0.3
NOMBRE_CLAVE_RT     = 'RT'
NOMBRE_CLAVE_PROY   = 'NOMBRE_PROYECTO'
TAMANO_LOTE         = 25

os.makedirs(RUTA_TEMP, exist_ok=True)

print(f"\n📍 Modo: {'Google Colab' if EN_COLAB else 'Local'}")
for ruta in RUTAS_ORIGEN:
    estado = "✅" if os.path.exists(ruta) else "❌"
    print(f"   {estado} {ruta}")

# ═══════════════════════════════════════════════════════════════════════════════════
# FUNCIONES JSON GENÉRICAS
# ═══════════════════════════════════════════════════════════════════════════════════
def cargar_json(ruta, default):
    if os.path.exists(ruta):
        try:
            with open(ruta, 'r', encoding='utf-8') as f:
                return json.load(f)
        except Exception as e:
            print(f"⚠️ Error cargando {os.path.basename(ruta)}: {e}")
    return default

def guardar_json(ruta, data):
    try:
        with open(ruta, 'w', encoding='utf-8') as f:
            json.dump(data, f, indent=2, ensure_ascii=False)
    except Exception as e:
        print(f"❌ Error guardando {os.path.basename(ruta)}: {e}")

# ═══════════════════════════════════════════════════════════════════════════════════
# ✅ SISTEMA DE PROGRESO REANUDABLE
# ═══════════════════════════════════════════════════════════════════════════════════
def calcular_hash_archivo(ruta):
    try:
        stat  = os.stat(ruta)
        clave = f"{ruta}|{stat.st_size}|{stat.st_mtime}"
        return hashlib.md5(clave.encode()).hexdigest()
    except:
        return None

def cargar_progreso():
    return cargar_json(RUTA_PROGRESO, {})

def guardar_progreso(progreso):
    guardar_json(RUTA_PROGRESO, progreso)

def limpiar_todo_para_empezar_de_cero():
    print("\n🧹 LIMPIANDO DATOS PROCESADOS ANTERIORES...")
    eliminados = 0
    for f in glob.glob(os.path.join(RUTA_TEMP, "lote_*.csv")):
        try:
            os.remove(f)
            eliminados += 1
        except:
            pass
    if os.path.exists(RUTA_PROGRESO):
        os.remove(RUTA_PROGRESO)
    if os.path.exists(RUTA_AUDITORIA_GEO):
        os.remove(RUTA_AUDITORIA_GEO)
    print(f"   🗑️ {eliminados} lotes eliminados")
    print(f"   🗑️ Progreso reiniciado")
    print(f"   💾 Memoria de hojas y columnas CONSERVADA")

# ═══════════════════════════════════════════════════════════════════════════════════
# FUNCIONES DE MEMORIA
# ═══════════════════════════════════════════════════════════════════════════════════
def cargar_memoria_columnas():
    mem = cargar_json(RUTA_MEMORIA_JSON, {})
    if mem:
        print(f"💾 Memoria columnas: {len(mem)} entradas")
    return mem

def guardar_memoria_columnas(d):
    guardar_json(RUTA_MEMORIA_JSON, d)

def cargar_memoria_hojas():
    return cargar_json(RUTA_MEMORIA_HOJAS, {})

def guardar_memoria_hojas(mem):
    guardar_json(RUTA_MEMORIA_HOJAS, mem)

def cargar_memoria_hojas_geo():
    return cargar_json(RUTA_MEMORIA_GEO, {})

def guardar_memoria_hojas_geo(mem):
    guardar_json(RUTA_MEMORIA_GEO, mem)

# ═══════════════════════════════════════════════════════════════════════════════════
# NORMALIZACIÓN
# ═══════════════════════════════════════════════════════════════════════════════════
def limpiar_texto(texto):
    if not isinstance(texto, str):
        return str(texto)
    texto = texto.upper()
    texto = unicodedata.normalize('NFD', texto).encode('ascii', 'ignore').decode('utf-8')
    texto = re.sub(r'[^A-Z0-9\s\.\-_]', ' ', texto)
    for sw in ['CL','KR','CR','DG','AC','AK','NRO','NO','NUM','NUMERO',
               'DE','LA','EL','LOS','LAS','O','Y','DEL','AL']:
        texto = re.sub(f'\\b{sw}\\b', ' ', texto)
    return " ".join(texto.split())

def normalizar_nombre(texto):
    if not isinstance(texto, str):
        return "DESCONOCIDO"
    texto = texto.upper()
    texto = unicodedata.normalize('NFD', texto).encode('ascii', 'ignore').decode('utf-8')
    texto = re.sub(r'[^A-Z0-9]', ' ', texto)
    return " ".join(texto.split())

def detectar_proyecto(ruta_relativa):
    partes = [p for p in ruta_relativa.split(os.sep) if p and p != '.']
    raw    = partes[2] if len(partes) >= 3 else (
             partes[1] if len(partes) >= 2 else (
             partes[0] if len(partes) >= 1 else "PROYECTO_GENERAL"))
    nombre = normalizar_nombre(raw)
    nombre = re.sub(r'\b\d{8}\b', '', nombre)
    nombre = re.sub(r'\b\d{6}\b', '', nombre)
    nombre = re.sub(r'\s+(XLSX|XLS|CSV)$', '', nombre)
    nombre = " ".join(nombre.split())
    return nombre if nombre else normalizar_nombre(raw)

# ═══════════════════════════════════════════════════════════════════════════════════
# VALIDACIÓN DE RT
# ═══════════════════════════════════════════════════════════════════════════════════
def es_fecha(valor):
    if pd.isna(valor) or valor is None:
        return False
    s = str(valor).strip()
    if not s or s.upper() in ['NAN','NAT','NONE','']:
        return False
    for pat in [r'^\d{1,2}[-/\.]\d{1,2}[-/\.]\d{2,4}$',
                r'^\d{4}[-/\.]\d{1,2}[-/\.]\d{1,2}$',
                r'^\d{2}:\d{2}:\d{2}$',
                r'^\d{4}-\d{2}-\d{2}\s\d{2}:\d{2}',
                r'^\d{1,2}\s+(ENE|FEB|MAR|ABR|MAY|JUN|JUL|AGO|SEP|OCT|NOV|DIC)']:
        if re.match(pat, s, re.IGNORECASE):
            return True
    meses = ['ENE','FEB','MAR','ABR','MAY','JUN','JUL','AGO','SEP','OCT','NOV','DIC',
             'ENERO','FEBRERO','MARZO','ABRIL','MAYO','JUNIO','JULIO','AGOSTO',
             'SEPTIEMBRE','OCTUBRE','NOVIEMBRE','DICIEMBRE',
             'JANUARY','FEBRUARY','MARCH','APRIL','JUNE','JULY','AUGUST',
             'SEPTEMBER','OCTOBER','NOVEMBER','DECEMBER']
    if any(m in s.upper() for m in meses):
        return True
    try:
        pd.to_datetime(s, errors='raise')
        if not re.search(r'\d{2}[-_]\d{3}', s):
            return True
    except:
        pass
    return False

def extraer_rt(valor):
    if isinstance(valor, pd.Series):
        valor = valor.iloc[0] if not valor.empty else None
    if pd.isna(valor) or valor is None:
        return None
    s = str(valor).strip().upper()

    if len(s) < 3 or len(s) > 40:
        return None
    if s.endswith('.0'):
        s = s[:-2]
    if es_fecha(s):
        return None
    if any(p in s for p in ['TOTAL','SUBTOTAL','SUMA','PROMEDIO','AVERAGE']):
        return None

    s = re.sub(r'^(RT|R\.T\.|R\s*T)\s*[-:]?\s*', '', s, flags=re.IGNORECASE).strip()

    if re.match(r'^\d{2,8}([\s\-]*[A-Z0-9]+)*$', s):
        return s

    m = re.search(r'(\d{2}[-_]\d{3,4}[A-Z]?)', s)
    if m: return m.group(1)

    if re.search(r'\d', s) and not s.isdigit():
        if re.search(r'[-_]|\d[A-Z]|[A-Z]\d', s):
            if not re.match(r'^(19|20)\d{2}$', s):
                return s
    return None

def depurar_columna_rt(df, col_rt, umbral_densidad=0.5):
    if col_rt not in df.columns:
        return df
    if isinstance(df[col_rt], pd.DataFrame):
        df = df.loc[:, ~df.columns.duplicated()]

    nuevos_rts = []
    total_cols = len(df.columns)

    for _, fila in df.iterrows():
        val_original = fila[col_rt]
        rt_limpio = extraer_rt(val_original)

        if rt_limpio is not None:
            nuevos_rts.append(rt_limpio)
        else:
            val_str = str(val_original).strip().upper()
            es_vacio = pd.isna(val_original) or val_str in ['NAN', 'NONE', 'NAT', ''] or len(val_str) < 2
            es_invalido = es_fecha(val_str) or any(p in val_str for p in ['TOTAL','SUBTOTAL','SUMA','PROMEDIO','AVERAGE'])

            if not es_vacio and not es_invalido:
                densidad = fila.notna().sum() / total_cols
                if densidad >= umbral_densidad:
                    rt_salvado = re.sub(r'^(RT|R\.T\.|R\s*T)\s*[-:]?\s*', '', val_str, flags=re.IGNORECASE).strip()
                    nuevos_rts.append(rt_salvado)
                else:
                    nuevos_rts.append(None)
            else:
                nuevos_rts.append(None)

    df = df.copy()
    df[col_rt] = nuevos_rts
    df_limpio = df.dropna(subset=[col_rt]).copy()

    diff = len(df) - len(df_limpio)
    if diff > 0:
        print(f"      🧹 {diff} filas eliminadas (Incompletas o sin RT)")

    return df_limpio

# ═══════════════════════════════════════════════════════════════════════════════════
# ✅ SELECCIÓN DE HOJAS
# ═══════════════════════════════════════════════════════════════════════════════════
def key_hojas(hojas):
    return "|".join(sorted(str(h).strip().lower() for h in hojas))

def hoja_bd_automatica(hojas):
    prioridades = [
        lambda h: str(h).strip().upper() == "BD",
        lambda h: str(h).strip().upper().startswith("BD"),
        lambda h: "BD" in str(h).strip().upper(),
        lambda h: "BASE" in str(h).strip().upper(),
    ]
    for criterio in prioridades:
        for h in hojas:
            if criterio(h):
                return h
    return None

def buscar_en_memoria_hojas(hojas, memoria):
    k = key_hojas(hojas)
    def obtener_nombre_limpio(valor):
        if isinstance(valor, dict):
            return str(valor.get('hoja_seleccionada', '')).strip().lower()
        return str(valor).strip().lower()

    if '__global__' in memoria and k in memoria['__global__']:
        hoja_guardada = obtener_nombre_limpio(memoria['__global__'][k])
        for h in hojas:
            if str(h).strip().lower() == hoja_guardada:
                return h, '__global__'
        if hoja_guardada == "ninguna": return "NINGUNA", '__global__'

    for proyecto, estructuras in memoria.items():
        if proyecto == '__global__': continue
        if k in estructuras:
            hoja_guardada = obtener_nombre_limpio(estructuras[k])
            for h in hojas:
                if str(h).strip().lower() == hoja_guardada:
                    return h, proyecto
            if hoja_guardada == "ninguna": return "NINGUNA", proyecto

    return None, None

def guardar_en_memoria_hojas(hojas, hoja_sel, proyecto, memoria, is_geo=False):
    k = key_hojas(hojas)
    if proyecto not in memoria:
        memoria[proyecto] = {}
    memoria[proyecto][k] = hoja_sel
    if '__global__' not in memoria:
        memoria['__global__'] = {}
    memoria['__global__'][k] = hoja_sel

    if is_geo:
        guardar_memoria_hojas_geo(memoria)
    else:
        guardar_memoria_hojas(memoria)

def seleccionar_hoja(archivo, hojas, proyecto, memoria_hojas):
    hoja_mem, origen = buscar_en_memoria_hojas(hojas, memoria_hojas)
    if hoja_mem:
        return hoja_mem

    hoja_auto = hoja_bd_automatica(hojas)
    if hoja_auto:
        print(f"   ✅ Hoja auto-detectada: '{hoja_auto}' | Proyecto: {proyecto}")
        guardar_en_memoria_hojas(hojas, hoja_auto, proyecto, memoria_hojas)
        return hoja_auto

    print(f"\n{'─'*60}")
    print(f"📄 SELECCIÓN DE HOJA BASE — se guardará y NO se volverá a pedir")
    print(f"   Archivo:  {archivo}")
    print(f"   Proyecto: {proyecto}")
    print(f"   Hojas disponibles:")
    for i, h in enumerate(hojas, 1):
        print(f"      [{i}] {h}")

    while True:
        try:
            idx = int(input(f"\n   Número de hoja con la BD: ").strip()) - 1
            if 0 <= idx < len(hojas):
                hoja_sel = hojas[idx]
                break
            print(f"   ❌ Número inválido (1-{len(hojas)})")
        except ValueError:
            print("   ❌ Escribe un número")

    print(f"   ✅ '{hoja_sel}' guardada — no se preguntará de nuevo")
    guardar_en_memoria_hojas(hojas, hoja_sel, proyecto, memoria_hojas)
    return hoja_sel

def hoja_geo_automatica(hojas):
    prioridades = [
        lambda h: str(h).strip().upper() == "GEOREFERENCIACIÓN",
        lambda h: str(h).strip().upper() == "GEOREFERENCIACION",
        lambda h: "GEOREFERENCIA" in str(h).strip().upper(),
        lambda h: "GEO" in str(h).strip().upper()
    ]
    for criterio in prioridades:
        for h in hojas:
            if criterio(h):
                return h
    return None

def seleccionar_hoja_geo(archivo, hojas, proyecto, memoria_hojas_geo):
    hoja_mem, origen = buscar_en_memoria_hojas(hojas, memoria_hojas_geo)
    if hoja_mem:
        return hoja_mem if hoja_mem != "NINGUNA" else None

    hoja_auto = hoja_geo_automatica(hojas)
    if hoja_auto:
        print(f"   📍 Hoja GEO auto-detectada: '{hoja_auto}'")
        guardar_en_memoria_hojas(hojas, hoja_auto, proyecto, memoria_hojas_geo, is_geo=True)
        return hoja_auto

    print(f"\n{'─'*60}")
    print(f"🌍 SELECCIÓN DE HOJA GEOREFERENCIACIÓN (se guardará y NO se volverá a pedir)")
    print(f"   Archivo:  {archivo}")
    print(f"   Hojas disponibles:")
    print(f"      [0] NO TIENE / OMITIR ❌")
    for i, h in enumerate(hojas, 1):
        print(f"      [{i}] {h}")

    while True:
        try:
            idx = int(input(f"\n   Número de hoja GEO (0 para omitir): ").strip())
            if idx == 0:
                hoja_sel = "NINGUNA"
                break
            elif 1 <= idx <= len(hojas):
                hoja_sel = hojas[idx-1]
                break
            print(f"   ❌ Número inválido (0-{len(hojas)})")
        except ValueError:
            print("   ❌ Escribe un número")

    print(f"   ✅ '{hoja_sel}' guardada en caché Geo")
    guardar_en_memoria_hojas(hojas, hoja_sel, proyecto, memoria_hojas_geo, is_geo=True)
    return hoja_sel if hoja_sel != "NINGUNA" else None

# ═══════════════════════════════════════════════════════════════════════════════════
# FUNCIONES EXCEL AUXILIARES
# ═══════════════════════════════════════════════════════════════════════════════════
def detectar_fila_encabezado(ruta, hoja):
    try:
        df = pd.read_excel(ruta, sheet_name=hoja, header=None, nrows=15, engine='openpyxl')
        mejor, max_txt = 0, 0
        for i, fila in df.iterrows():
            cnt = fila.apply(lambda x: isinstance(x, str) and len(str(x).strip()) > 1).sum()
            if cnt > max_txt:
                max_txt, mejor = cnt, i
        return mejor
    except:
        return 0

def es_col_rt(nombre):
    n = limpiar_texto(nombre)
    for pat in [r'^RT$', r'^R\s*T$', r'^R\.?\s*T\.?$', r'^RT\s+']:
        if re.match(pat, n, re.IGNORECASE):
            return True
    return False

def ejemplos_col(df, col, n=3):
    try:
        return [str(v)[:50] for v in df[col].dropna().head(n).tolist()]
    except:
        return []

def fecha_de_archivo(nombre, ruta=None):
    for pat in [r'(\d{2})(\d{2})(\d{4})', r'(\d{4})[-_](\d{2})[-_](\d{2})',
                r'(\d{2})[-_](\d{2})[-_](\d{4})']:
        m = re.search(pat, nombre)
        if m:
            g = m.groups()
            combos = [(g[2],g[1],g[0]), (g[0],g[1],g[2])]
            for y,mo,d in combos:
                try:
                    f = datetime(int(y), int(mo), int(d))
                    if 2000 <= f.year <= 2030:
                        return f
                except:
                    pass
    if ruta and os.path.exists(ruta):
        try:
            return datetime.fromtimestamp(os.path.getmtime(ruta))
        except:
            pass
    return datetime(1900, 1, 1)

# ═══════════════════════════════════════════════════════════════════════════════════
# INFERENCIA DE TIPOS
# ═══════════════════════════════════════════════════════════════════════════════════
def inferir_tipo(serie):
    if serie.empty:
        return 'VACIO'
    muestra = serie.dropna().head(100)
    if muestra.empty:
        return 'VACIO'
    n = es_f = es_b = es_t = 0
    for v in muestra:
        s = str(v).strip()
        if s.upper() in ['SI','NO','TRUE','FALSE','1','0','S','N']:
            es_b += 1; continue
        try:
            float(s.replace(',','').replace('$','').replace('%','')); n += 1; continue
        except: pass
        try:
            pd.to_datetime(s, errors='raise'); es_f += 1; continue
        except: pass
        es_t += 1
    total = len(muestra)
    if n/total > 0.7:      return 'NUMERICO'
    elif es_f/total > 0.6: return 'FECHA'
    elif es_b/total > 0.6: return 'BOOLEANO'
    elif es_t/total > 0.6: return 'TEXTO'
    else:                  return 'MIXTO'

# ═══════════════════════════════════════════════════════════════════════════════════
# MOTOR DE SIMILITUD
# ═══════════════════════════════════════════════════════════════════════════════════
class MotorSimilitud:
    def __init__(self):
        self.modelo = None
        if USAR_IA_SEMANTICA:
            try:
                print("🤖 Cargando modelo IA...")
                self.modelo = SentenceTransformer('paraphrase-multilingual-MiniLM-L12-v2')
                print("✅ Modelo IA listo")
            except Exception as e:
                print(f"⚠️ Sin modelo IA: {e}")

    def sim_nombre(self, a, b):
        score = fuzz.token_set_ratio(a, b)
        if self.modelo:
            try:
                e1 = self.modelo.encode([a])
                e2 = self.modelo.encode([b])
                score = score * 0.6 + cosine_similarity(e1, e2)[0][0] * 100 * 0.4
            except: pass
        return score

    def sim_tipo(self, t1, t2):
        if t1 == t2: return 100.0
        for grupo in [{'NUMERICO','MIXTO'},{'TEXTO','MIXTO'},
                      {'FECHA','TEXTO'},{'BOOLEANO','TEXTO'}]:
            if {t1,t2}.issubset(grupo): return 70.0
        return 0.0

    def score(self, n1, n2, t1, t2):
        sn = self.sim_nombre(n1, n2)
        st = self.sim_tipo(t1, t2)
        return {'score_total': round(sn*PESO_NOMBRE + st*PESO_TIPO, 2),
                'score_nombre': round(sn, 2), 'score_tipo': round(st, 2)}

def conflicto_numerico(a, b):
    n1 = set(re.findall(r'\d{4}', a))
    n2 = set(re.findall(r'\d{4}', b))
    return bool(n1 and n2 and n1 != n2)

# ═══════════════════════════════════════════════════════════════════════════════════
# ✅ FASE 1: PROCESAMIENTO REANUDABLE
# ═══════════════════════════════════════════════════════════════════════════════════
def fase1_procesar_archivos():
    print("\n" + "="*80)
    print("🔍 FASE 1: PROCESAMIENTO REANUDABLE")
    print("   ✅ Retoma desde donde quedó si fue interrumpido")
    print("   ✅ Reprocesa archivos modificados automáticamente")
    print("="*80)

    mapa_col      = cargar_memoria_columnas()
    mem_hojas     = cargar_memoria_hojas()
    mem_hojas_geo = cargar_memoria_hojas_geo()
    progreso      = cargar_progreso()
    rts_geo_global= set(cargar_json(RUTA_AUDITORIA_GEO, []))

    todos = []
    print("\n📂 Escaneando carpetas...")
    for ruta_base in RUTAS_ORIGEN:
        if not os.path.exists(ruta_base):
            print(f"   ⚠️ No existe: {ruta_base}")
            continue
        print(f"   ✅ {ruta_base}")
        for root, _, files in os.walk(ruta_base):
            for f in files:
                if f.endswith(('.xlsx','.xls')) and not f.startswith('~$'):
                    todos.append(os.path.join(root, f))

    total = len(todos)
    print(f"\n📊 Total archivos encontrados: {total:,}")

    if total == 0:
        print("⚠️ No hay archivos Excel")
        return None

    pendientes   = []
    ya_listos    = 0
    modificados  = 0

    for path in todos:
        hash_actual = calcular_hash_archivo(path)
        if path in progreso:
            info = progreso[path]

            lote_guardado = info.get('lote_csv', '')
            if lote_guardado:
                nombre_lote = os.path.basename(lote_guardado)
                lote_real = os.path.join(RUTA_TEMP, nombre_lote)
            else:
                lote_real = ''

            lote_existe = os.path.exists(lote_real)
            hash_igual  = info.get('hash') == hash_actual

            if lote_existe and hash_igual:
                ya_listos += 1
                continue
            else:
                modificados += 1
                pendientes.append((path, hash_actual))
        else:
            pendientes.append((path, hash_actual))

    print(f"   ✅ Ya procesados (con lote):  {ya_listos:,}")
    print(f"   🔄 Modificados/sin lote:      {modificados:,}")
    print(f"   ⏳ Nuevos a procesar:         {len(pendientes) - modificados:,}")
    print(f"   📋 Total a procesar ahora:    {len(pendientes):,}")

    if not pendientes:
        print("\n✅ Todos los archivos ya tienen lote. Pasando a consolidación.")
        return cargar_metadatos_de_progreso(progreso)

    lote_dfs     = []
    lote_num     = obtener_ultimo_lote_num() + 1
    metadatos    = defaultdict(lambda: {'tipos':[], 'frecuencia':0, 'ejemplos':[]})
    log          = []
    stats        = {'ok':0, 'sin_rt':0, 'error':0, 'vacio':0}
    progreso_nuevo = {}

    print(f"\n🚀 Procesando {len(pendientes)} archivos...\n")

    for idx, (path, hash_arch) in enumerate(pendientes, 1):
        nombre = os.path.basename(path)
        pct    = (idx / len(pendientes)) * 100
        print(f"   [{idx:>4}/{len(pendientes)}] {pct:5.1f}% | {nombre[:55]}", end='\r')

        log.append(f"\n{'='*60}\n[{idx}] {nombre}")

        try:
            ruta_base = next((r for r in RUTAS_ORIGEN if path.startswith(r)), RUTAS_ORIGEN[0])
            ruta_rel  = os.path.relpath(path, ruta_base)
            proyecto  = detectar_proyecto(ruta_rel)

            xl    = pd.ExcelFile(path, engine='openpyxl')
            hojas = xl.sheet_names
            hoja  = seleccionar_hoja(nombre, hojas, proyecto, mem_hojas)
            fila_enc = detectar_fila_encabezado(path, hoja)

            df = pd.read_excel(path, sheet_name=hoja, header=fila_enc,
                               nrows=5000, engine='openpyxl')
            df = df.dropna(how='all')

            if df.empty:
                log.append("⚠️ Vacío"); stats['vacio'] += 1; xl.close(); del xl; continue

            cols_nuevas = []
            cols_rt     = []
            for col in df.columns:
                if not col or str(col).strip() == '' or pd.isna(col):
                    cols_nuevas.append(col); continue
                cl = limpiar_texto(col)
                tp = inferir_tipo(df[col])
                ej = ejemplos_col(df, col)
                metadatos[cl]['tipos'].append(tp)
                metadatos[cl]['frecuencia'] += 1
                if len(metadatos[cl]['ejemplos']) < 5:
                    metadatos[cl]['ejemplos'].extend(ej)
                    metadatos[cl]['ejemplos'] = metadatos[cl]['ejemplos'][:5]
                mapeada = mapa_col.get(cl, cl)
                if cl not in mapa_col:
                    mapa_col[cl] = cl
                cols_nuevas.append(mapeada)
                if es_col_rt(col):
                    cols_rt.append(mapeada)

            df.columns = cols_nuevas
            df = df.loc[:, ~df.columns.duplicated(keep='last')]

            if cols_rt:
                col_rt = cols_rt[0]
                if col_rt != NOMBRE_CLAVE_RT:
                    df.rename(columns={col_rt: NOMBRE_CLAVE_RT}, inplace=True)
            elif NOMBRE_CLAVE_RT in df.columns:
                pass
            else:
                log.append("❌ Sin RT"); stats['sin_rt'] += 1; xl.close(); del xl; continue

            df = depurar_columna_rt(df, NOMBRE_CLAVE_RT, umbral_densidad=0.5)

            if df.empty:
                log.append("⚠️ Sin RTs válidos"); stats['vacio'] += 1; xl.close(); del xl; continue

            fecha_arch = fecha_de_archivo(nombre, path)
            df.insert(0, NOMBRE_CLAVE_PROY, proyecto)
            df['FECHA_ARCHIVO']  = fecha_arch
            df['ARCHIVO_ORIGEN'] = nombre

            # ═══════════════════════════════════════════════════════════════════════════════════
            # ✅ GEOREFERENCIACIÓN
            # ═══════════════════════════════════════════════════════════════════════════════════
            hoja_geo = seleccionar_hoja_geo(nombre, hojas, proyecto, mem_hojas_geo)

            if hoja_geo:
                try:
                    df_geo = pd.read_excel(path, sheet_name=hoja_geo, header=detectar_fila_encabezado(path, hoja_geo), engine='openpyxl')
                    cols_rt_geo = [c for c in df_geo.columns if es_col_rt(str(c))]

                    if cols_rt_geo:
                        col_rt_geo = cols_rt_geo[0]
                        df_geo['__RT_JOIN__'] = df_geo[col_rt_geo].apply(extraer_rt)
                        df_geo = df_geo.dropna(subset=['__RT_JOIN__']).drop_duplicates(subset=['__RT_JOIN__'])

                        col_estado = next((c for c in df_geo.columns if "ESTADO" in str(c).upper()), None)
                        col_obs    = next((c for c in df_geo.columns if "OBSERVACI" in str(c).upper()), None)

                        if not col_estado and len(df_geo.columns) > 8: col_estado = df_geo.columns[8]
                        if not col_obs and len(df_geo.columns) > 9:    col_obs    = df_geo.columns[9]

                        def determinar_estado(val):
                            s = str(val).strip().upper()
                            if pd.isna(val) or s in ['#N/A', '#N/D', 'NAN', '<NA>', '', 'NONE']:
                                return 'INACTIVO'
                            return 'ACTIVO'

                        if col_estado in df_geo.columns:
                            df_geo['INACTIVO/ACTIVO'] = df_geo[col_estado].apply(determinar_estado)
                        else:
                            df_geo['INACTIVO/ACTIVO'] = 'ACTIVO'

                        if col_obs in df_geo.columns:
                            df_geo['OBSERVACIÓN INACTIVO/ACTIVO'] = df_geo[col_obs]
                        else:
                            df_geo['OBSERVACIÓN INACTIVO/ACTIVO'] = None

                        rts_geo_global.update(df_geo['__RT_JOIN__'].tolist())

                        df = pd.merge(df, df_geo[['__RT_JOIN__', 'INACTIVO/ACTIVO', 'OBSERVACIÓN INACTIVO/ACTIVO']],
                                      left_on=NOMBRE_CLAVE_RT, right_on='__RT_JOIN__', how='outer')

                        df[NOMBRE_CLAVE_RT] = df[NOMBRE_CLAVE_RT].fillna(df['__RT_JOIN__'])
                        df.drop(columns=['__RT_JOIN__'], inplace=True)

                        df[NOMBRE_CLAVE_PROY] = df[NOMBRE_CLAVE_PROY].fillna(proyecto)
                        df['FECHA_ARCHIVO'] = df['FECHA_ARCHIVO'].fillna(fecha_arch)
                        df['ARCHIVO_ORIGEN'] = df['ARCHIVO_ORIGEN'].fillna(nombre)
                    else:
                        df['INACTIVO/ACTIVO'] = None
                        df['OBSERVACIÓN INACTIVO/ACTIVO'] = None
                except Exception as e_geo:
                    log.append(f"⚠️ Error leyendo GEOREFERENCIACIÓN en {nombre}: {e_geo}")
                    df['INACTIVO/ACTIVO'] = None
                    df['OBSERVACIÓN INACTIVO/ACTIVO'] = None
            else:
                df['INACTIVO/ACTIVO'] = None
                df['OBSERVACIÓN INACTIVO/ACTIVO'] = None

            log.append(f"✅ {len(df)} registros | {fecha_arch.strftime('%Y-%m-%d')}")
            stats['ok'] += 1
            lote_dfs.append(df)

            xl.close(); del xl

        except Exception as e:
            log.append(f"❌ {str(e)[:100]}"); stats['error'] += 1; continue

        if len(lote_dfs) >= TAMANO_LOTE or idx == len(pendientes):
            if lote_dfs:
                lote_path = os.path.join(RUTA_TEMP, f"lote_{lote_num:04d}.csv")
                try:
                    df_lote = pd.concat(lote_dfs, ignore_index=True)
                    df_lote.to_csv(lote_path, sep=';', index=False, encoding='utf-8-sig')
                    print(f"\n   💾 Lote {lote_num}: {len(df_lote):,} registros → {os.path.basename(lote_path)}")
                    for (p, h) in pendientes[max(0,idx-len(lote_dfs)):idx]:
                        progreso_nuevo[p] = {
                            'hash':     h,
                            'lote_csv': lote_path,
                            'fecha':    datetime.now().isoformat()
                        }
                    del df_lote
                except Exception as e:
                    print(f"\n   ⚠️ Error guardando lote: {e}")
                lote_dfs = []
                lote_num += 1
                gc.collect()

            progreso.update(progreso_nuevo)
            guardar_progreso(progreso)
            guardar_memoria_columnas(mapa_col)
            guardar_json(RUTA_AUDITORIA_GEO, list(rts_geo_global))
            progreso_nuevo = {}

    with open(RUTA_LOG, 'w', encoding='utf-8') as f:
        f.write('\n'.join(log))

    print(f"\n\n{'='*60}")
    print(f"✅ FASE 1 COMPLETADA")
    print(f"   ✅ OK:          {stats['ok']:,}")
    print(f"   ❌ Sin RT:      {stats['sin_rt']:,}")
    print(f"   ⚠️  Vacíos:     {stats['vacio']:,}")
    print(f"   💥 Errores:     {stats['error']:,}")
    print(f"   📝 Log: {RUTA_LOG}")

    return dict(metadatos) if metadatos else None

def obtener_ultimo_lote_num():
    lotes = glob.glob(os.path.join(RUTA_TEMP, "lote_*.csv"))
    if not lotes: return 0
    nums = []
    for l in lotes:
        m = re.search(r'lote_(\d+)', os.path.basename(l))
        if m: nums.append(int(m.group(1)))
    return max(nums) if nums else 0

def cargar_metadatos_de_progreso(progreso):
    return None

# ═══════════════════════════════════════════════════════════════════════════════════
# FASE 2: HOMOLOGACIÓN DE COLUMNAS
# ═══════════════════════════════════════════════════════════════════════════════════
def fase2_homologar_columnas(metadatos):
    if not metadatos:
        print("\n⏭️ Sin columnas nuevas, omitiendo homologación")
        return cargar_memoria_columnas()

    print("\n" + "="*80)
    print("🧠 FASE 2: HOMOLOGACIÓN DE COLUMNAS")
    print("="*80)

    mapa   = cargar_memoria_columnas()
    config = cargar_json(RUTA_CONFIG_MAPEO, {})
    motor  = MotorSimilitud()

    meta_final = {}
    for col, info in metadatos.items():
        if isinstance(info, dict):
            tipos = info.get('tipos', [])
            tipo  = Counter(tipos).most_common(1)[0][0] if tipos else 'TEXTO'
            meta_final[col] = {
                'tipo':       tipo,
                'frecuencia': info.get('frecuencia', 1),
                'ejemplos':   info.get('ejemplos', [])[:5]
            }
        else:
            meta_final[col] = {'tipo':'TEXTO','frecuencia':1,'ejemplos':[]}

    maestras = {NOMBRE_CLAVE_RT: 'TEXTO'}
    for col_orig, col_oficial in mapa.items():
        if col_oficial not in maestras and col_oficial in meta_final:
            maestras[col_oficial] = meta_final[col_oficial]['tipo']

    nuevas = [c for c in sorted(meta_final, key=lambda x: meta_final[x]['frecuencia'], reverse=True)
              if c not in mapa]
    print(f"\n📊 Columnas nuevas a homologar: {len(nuevas)}")

    pendientes_val = []

    for i, col in enumerate(nuevas, 1):
        tipo     = meta_final[col]['tipo']
        ejemplos = meta_final[col]['ejemplos']

        if es_col_rt(col):
            mapa[col] = NOMBRE_CLAVE_RT
            print(f"   ✅ RT [{i}/{len(nuevas)}]: '{col}'")
            continue
        if tipo == 'VACIO':
            continue

        candidatos = []
        for maestra, tipo_m in maestras.items():
            if conflicto_numerico(col, maestra):
                continue
            s = motor.score(col, maestra, tipo, tipo_m)
            if s['score_total'] >= UMBRAL_PREGUNTA_MIN:
                candidatos.append({'columna': maestra, 'tipo': tipo_m, **s})

        candidatos.sort(key=lambda x: x['score_total'], reverse=True)
        asignada = False

        if candidatos:
            mejor = candidatos[0]
            if mejor['score_total'] >= UMBRAL_AUTO:
                mapa[col] = mejor['columna']
                asignada  = True
                print(f"   ✅ AUTO [{i}]: '{col}' → '{mejor['columna']}' ({mejor['score_total']}%)")
            else:
                print(f"\n   ⚠️ DECISIÓN [{i}/{len(nuevas)}] ({mejor['score_total']}%)")
                print(f"      Nueva:     '{col}' ({tipo}) | Ej: {ejemplos}")
                print(f"      Candidato: '{mejor['columna']}' ({mejor['tipo']})")
                if mejor['columna'] in meta_final:
                    print(f"      Ej.cand.:  {meta_final[mejor['columna']]['ejemplos']}")
                resp = input("      ¿Unir? (s/n): ").lower().strip()
                if resp == 's':
                    mapa[col] = mejor['columna']
                    asignada  = True
                    print("      ✅ Unido")
                else:
                    pendientes_val.append({'col': col, 'candidato': mejor['columna'],
                                           'score': mejor['score_total']})
                    print("      ❌ Separado")

        if not asignada:
            maestras[col] = tipo
            mapa[col]     = col
            print(f"   ➕ NUEVA [{i}]: '{col}'")

    guardar_memoria_columnas(mapa)
    guardar_json(RUTA_CONFIG_MAPEO, config)
    guardar_json(RUTA_VALIDACIONES, pendientes_val)
    print(f"\n✅ FASE 2 COMPLETADA | Maestras: {len(maestras)} | Pend: {len(pendientes_val)}")
    return mapa

# ═══════════════════════════════════════════════════════════════════════════════════
# ✅ FASE 3: CONSOLIDACIÓN (OPTIMIZADA RAM, ORDEN Y FUSIÓN HISTÓRICA)
# ═══════════════════════════════════════════════════════════════════════════════════
def fase3_consolidar():
    print("\n" + "="*80)
    print("🔄 FASE 3: CONSOLIDACIÓN FINAL (OPTIMIZADA EN RAM)")
    print("   ✅ Concatenación iterativa para evitar caídas de memoria")
    print("   ✅ Fusión inteligente de historiales para RTs inactivos")
    print("   ✅ Ordenamiento persistente por Proyecto y RT")
    print("="*80)

    lotes = sorted(glob.glob(os.path.join(RUTA_TEMP, "lote_*.csv")))
    if not lotes:
        print("⚠️ No hay lotes para consolidar")
        return

    print(f"\n📚 Lotes encontrados: {len(lotes)}")

    rts_historicos = set()
    orden_proyectos = {}
    orden_rts = {}
    es_primera_vez = not os.path.exists(RUTA_SALIDA)

    if not es_primera_vez:
        try:
            print("⏳ Leyendo histórico para mantener el orden y detectar RTs nuevos...")
            df_hist = pd.read_csv(RUTA_SALIDA, sep=';', usecols=lambda c: c in [NOMBRE_CLAVE_RT, NOMBRE_CLAVE_PROY], dtype=str, low_memory=False)
            rts_historicos = set(df_hist[NOMBRE_CLAVE_RT].dropna())

            proy_list = df_hist[NOMBRE_CLAVE_PROY].dropna().unique()
            orden_proyectos = {p: i for i, p in enumerate(proy_list)}

            orden_rts = {rt: i for i, rt in enumerate(df_hist[NOMBRE_CLAVE_RT].dropna())}
            del df_hist; gc.collect()
        except Exception as e:
            print(f"   ⚠️ No se pudo leer el histórico de ordenamiento: {e}")
            es_primera_vez = True

    print(f"\n🔗 Concatenando y fusionando historiales de {len(lotes)} lotes paso a paso...")
    df_final = pd.DataFrame()
    total_antes = 0

    for i, f in enumerate(lotes, 1):
        print(f"   [{i}/{len(lotes)}] Procesando: {os.path.basename(f)}", end='\r')
        try:
            df_temp = pd.read_csv(f, sep=';', encoding='utf-8-sig', low_memory=False)
            total_antes += len(df_temp)

            if 'FECHA_ARCHIVO' in df_temp.columns:
                df_temp['FECHA_ARCHIVO'] = pd.to_datetime(df_temp['FECHA_ARCHIVO'], errors='coerce').fillna(pd.Timestamp('1900-01-01'))

            df_final = pd.concat([df_final, df_temp], ignore_index=True)
            del df_temp

            # 🚨 CIRUGÍA: Fusionar incrementalmente para liberar RAM en bucle
            if i % 3 == 0 or i == len(lotes):
                df_final.sort_values('FECHA_ARCHIVO', ascending=False, inplace=True, na_position='last')
                # En lugar de eliminar duplicados, agrupamos y tomamos el primer valor no nulo de cada columna
                df_final = df_final.groupby(NOMBRE_CLAVE_RT, as_index=False, sort=False).first()
                gc.collect()

        except Exception as e:
            print(f"\n   ⚠️ Error leyendo {f} → {e}")

    if df_final.empty:
        print("\n❌ El dataframe final está vacío")
        return

    rts_final = df_final[NOMBRE_CLAVE_RT].nunique()
    total_final = len(df_final)
    eliminados = total_antes - total_final

    print(f"\n\n✅ FUSIÓN Y DEDUPLICACIÓN COMPLETADA:")
    print(f"   Pool histórico/bruto:   ~{total_antes:,} registros procesados")
    print(f"   RTs únicos finales:      {rts_final:,}")
    print(f"   Filas fusionadas/elim.:  {eliminados:,}")

    if es_primera_vez:
        df_final['CONTROL_NUEVO'] = ''
    else:
        df_final['CONTROL_NUEVO'] = df_final[NOMBRE_CLAVE_RT].apply(lambda x: 'NUEVO' if x not in rts_historicos else '')

    print("📏 Restaurando orden de proyectos...")
    nuevos_proys = sorted([p for p in df_final[NOMBRE_CLAVE_PROY].dropna().unique() if p not in orden_proyectos])
    max_idx = max(orden_proyectos.values()) if orden_proyectos else 0
    for p in nuevos_proys:
        max_idx += 1
        orden_proyectos[p] = max_idx

    df_final['_ORD_PROY'] = df_final[NOMBRE_CLAVE_PROY].map(orden_proyectos).fillna(999999)
    df_final['_ORD_RT'] = df_final[NOMBRE_CLAVE_RT].map(orden_rts).fillna(999999999)

    df_final.sort_values(['_ORD_PROY', '_ORD_RT', 'FECHA_ARCHIVO'], ascending=[True, True, True], inplace=True)
    df_final.drop(columns=['_ORD_PROY', '_ORD_RT'], inplace=True)
    df_final.reset_index(drop=True, inplace=True)
    gc.collect()

    prio = [NOMBRE_CLAVE_RT, NOMBRE_CLAVE_PROY, 'FECHA_ARCHIVO', 'ARCHIVO_ORIGEN']
    prio_ok = [c for c in prio if c in df_final.columns]

    columnas_finales = ['INACTIVO/ACTIVO', 'OBSERVACIÓN INACTIVO/ACTIVO', 'CONTROL_NUEVO']
    otras = sorted([c for c in df_final.columns if c not in prio and c not in columnas_finales])
    finales_ok = [c for c in columnas_finales if c in df_final.columns]

    df_final = df_final[prio_ok + otras + finales_ok]

    print(f"\n💾 Guardando {RUTA_SALIDA}...")
    df_final.to_csv(RUTA_SALIDA, sep=';', index=False, encoding='utf-8-sig')
    tam = os.path.getsize(RUTA_SALIDA) / (1024*1024)
    print(f"   ✅ {tam:.2f} MB")

    with open(RUTA_REPORT_TXT, 'w', encoding='utf-8') as f:
        f.write("="*80 + "\nREPORTE V21.0 — REANUDABLE + SIN PÉRDIDA DE RTs\n" + "="*80 + "\n\n")
        f.write(f"Fecha:    {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}\n\n")
        f.write(f"Pool global:       {total_antes:,}\n")
        f.write(f"Registros únicos:  {total_final:,}\n")
        f.write(f"Duplicados elim.:  {eliminados:,}\n")
        f.write(f"RTs únicos:        {rts_final:,}\n")
        f.write(f"Columnas:          {len(df_final.columns)}\n")
        f.write(f"Tamaño:            {tam:.2f} MB\n\n")
        f.write("COLUMNAS:\n" + "─"*60 + "\n")
        for i, col in enumerate(df_final.columns, 1):
            pct = df_final[col].notna().sum() / len(df_final) * 100
            f.write(f"  {i:3d}. {col:<50} ({pct:5.1f}%)\n")
        if NOMBRE_CLAVE_PROY in df_final.columns:
            f.write("\nPOR PROYECTO:\n" + "─"*60 + "\n")
            for proy, grp in df_final.groupby(NOMBRE_CLAVE_PROY):
                f.write(f"  {proy}: {len(grp):,} registros | {grp[NOMBRE_CLAVE_RT].nunique():,} RTs\n")
    print(f"   ✅ Reporte: {RUTA_REPORT_TXT}")

    # ═══════════════════════════════════════════════════════════════════════════════════
    # 🚨 AUDITORÍA DE GEOREFERENCIACIÓN
    # ═══════════════════════════════════════════════════════════════════════════════════
    print("\n" + "="*80)
    print("🔎 AUDITORÍA DE 100% RTs DE GEOREFERENCIACIÓN")
    print("="*80)
    audit_geo_cache = cargar_json(RUTA_AUDITORIA_GEO, [])
    rts_geo_totales = set(audit_geo_cache)
    rts_consolidados = set(df_final[NOMBRE_CLAVE_RT].dropna().unique())

    rts_faltantes = rts_geo_totales - rts_consolidados

    if len(rts_geo_totales) == 0:
        print("   ℹ️ No se detectaron RTs en hojas de georreferenciación.")
    elif len(rts_faltantes) == 0:
        print(f"   ✅ AUDITORÍA EXITOSA: El 100% de los RTs de GEO ({len(rts_geo_totales):,}) están en el consolidado final.")
    else:
        print(f"   ❌ ADVERTENCIA: Faltan {len(rts_faltantes):,} RTs de GEO en el archivo final.")
        print(f"      Ejemplos faltantes: {list(rts_faltantes)[:5]}")

    resp = input("\n🧹 ¿Eliminar lotes temporales? (s/n): ").lower().strip()
    if resp == 's':
        for lt in lotes:
            try: os.remove(lt)
            except: pass
        if os.path.exists(RUTA_PROGRESO):
            os.remove(RUTA_PROGRESO)
        print(f"   ✅ Lotes y progreso eliminados")
    else:
        print(f"   ℹ️ Conservados en: {RUTA_TEMP}")

    print(f"\n{'='*80}\n🎉 CONSOLIDACIÓN COMPLETADA")
    print(f"   ✅ Registros: {total_final:,} | RTs: {rts_final:,} | Columnas: {len(df_final.columns)}")
    del df_final; gc.collect()

# ═══════════════════════════════════════════════════════════════════════════════════
# EJECUCIÓN PRINCIPAL
# ═══════════════════════════════════════════════════════════════════════════════════
if __name__ == "__main__":
    print("\n" + "="*80)
    print("SISTEMA DE CONSOLIDACIÓN V21.0")
    print("✅ Reanudable | ✅ Sin pérdida de RTs | ✅ Memoria de hojas persistente")
    print("="*80)

    carpetas_ok = [r for r in RUTAS_ORIGEN if os.path.exists(r)]
    if not carpetas_ok:
        print("\n❌ Ninguna carpeta origen encontrada:")
        for r in RUTAS_ORIGEN: print(f"   - {r}")
        sys.exit(1)

    for c in carpetas_ok:
        n = sum(1 for _,_,fs in os.walk(c)
                for f in fs if f.endswith(('.xlsx','.xls')) and not f.startswith('~$'))
        print(f"   📂 {c} → {n:,} archivos")

    progreso_actual = cargar_progreso()
    lotes_existentes = glob.glob(os.path.join(RUTA_TEMP, "lote_*.csv"))

    print(f"\n{'─'*80}")
    if progreso_actual or lotes_existentes:
        print(f"📌 Se encontró progreso previo:")
        print(f"   Archivos registrados: {len(progreso_actual):,}")
        print(f"   Lotes generados:      {len(lotes_existentes):,}")
        print(f"\n   [1] Continuar desde donde quedó (recomendado)")
        print(f"   [2] Empezar de cero (borra lotes y progreso, conserva memoria hojas/columnas)")
        print(f"   [3] Cancelar")
        opcion = input("\n   Opción: ").strip()
        if opcion == '2':
            limpiar_todo_para_empezar_de_cero()
        elif opcion == '3':
            print("⏹️ Cancelado"); sys.exit(0)
        else:
            print("▶️ Continuando desde el progreso guardado...")
    else:
        print("🆕 No hay progreso previo — iniciando desde cero")
        resp = input("\n¿Iniciar? (s/n): ").lower().strip()
        if resp != 's':
            print("⏹️ Cancelado"); sys.exit(0)

    t0 = datetime.now()
    try:
        metadatos = fase1_procesar_archivos()
        if metadatos:
            fase2_homologar_columnas(metadatos)
        else:
            print("\n⏭️ Sin columnas nuevas, saltando homologación")
        fase3_consolidar()
    except KeyboardInterrupt:
        print(f"\n\n⚠️ Interrumpido — progreso guardado en {RUTA_PROGRESO}")
        print(f"   Ejecuta de nuevo y elige 'Continuar' para retomar")
        sys.exit(1)
    except Exception as e:
        print(f"\n\n❌ ERROR: {e}")
        import traceback; traceback.print_exc()
        sys.exit(1)

    tf = datetime.now()
    print(f"\n⏱️ Tiempo total: {tf - t0}")
    for arch in [RUTA_SALIDA, RUTA_REPORT_TXT, RUTA_LOG, RUTA_MEMORIA_JSON, RUTA_MEMORIA_HOJAS, RUTA_MEMORIA_GEO]:
        if os.path.exists(arch):
            kb = os.path.getsize(arch)/1024
            print(f"   ✅ {os.path.basename(arch):<45} ({'%.1f MB'%(kb/1024) if kb>1024 else '%.1f KB'%kb})")
        else:
            print(f"   ❌ {os.path.basename(arch)}")
    print("="*80)